In [ ]:
Numpy
- Numpy works closer to hardware
- Numpy performs scientific computations faster
- Numpy performs higher level computations easily
- performs array oriented programming

In [1]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(type(a))

b = np.arange(10)
print(b)
print(type(b))

[0 1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
More Efficient

In [10]:
a = range(1000)
print(type(a))
%timeit [i**2 for i in a]
%timeit [a]

<class 'range'>
1000 loops, best of 3: 363 µs per loop
10000000 loops, best of 3: 69.4 ns per loop


In [11]:
a = np.arange(1000)
print(type(a))
%timeit [i**2 for i in a]
%timeit [a]

<class 'numpy.ndarray'>
1000 loops, best of 3: 502 µs per loop
10000000 loops, best of 3: 68.4 ns per loop


In [14]:
ar = np.array([[0,1,2],[2,3,4]])
print(ar)
print(type(ar))

[[0 1 2]
 [2 3 4]]
<class 'numpy.ndarray'>


In [15]:
print(ar.ndim)

2


In [16]:
print(ar.shape)

(2, 3)


In [18]:
print(len(ar))           # returns first dimension

2


In [26]:
new = np.array([[[0,1],[1,2]],[[1,2],[2,3]]])
print(new)

[[[0 1]
  [1 2]]

 [[1 2]
  [2 3]]]


In [22]:
print(new.ndim)

3


In [23]:
print(new.shape)

(2, 2, 2)


In [27]:
print(len(new))

2


In [30]:
## Functions for creating array
fun = np.arange(10)
print(fun)
print(type(fun))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [31]:
fun = np.arange(1,10,2)   #start,end,stepsize
print(fun)

[1 3 5 7 9]


In [33]:
fun = np.linspace(1,10,7)   #start,end,number of points
fun = np.linspace(0,1,7)
print(fun)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [34]:
a = np.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [40]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
a = np.eye(4,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [43]:
dia = np.diag([1,2,3,4])                # construct a diagonal array
print(dia)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [46]:
n = np.diag(dia)                        # extract diagonal
print(n)
print(np.diag(dia))

[1 2 3 4]
[1 2 3 4]


In [48]:
## Creating array using random numbers

arr = np.random.rand(4)
print(type(arr))                           # uniform distributed random number
print(arr)

<class 'numpy.ndarray'>
[0.6344924  0.92623899 0.17509995 0.16423942]


In [49]:
arr = np.random.randn(4)
print(type(arr))                           # Guassian distributed & standard normal variate
print(arr)

<class 'numpy.ndarray'>
[-1.77668205  0.01988327 -0.03404063 -1.35513466]


In [50]:
# Basic datatypes

arr1 = np.arange(10)
print(arr1)
arr1.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int64')

In [51]:
arr1 = np.arange(10,dtype='float64')              # specified explicitly
print(arr1)                                             
arr1.dtype

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [57]:
a = np.ones((4,4),dtype='int')               # default datatypes for ones & zeros are float64
print(a)
print(a.dtype)

a1 = np.ones((2,3))
print(a1)
print(a1.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64
[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [59]:
a = np.zeros((4,4),dtype='int')               # default datatypes for ones & zeros are float64
print(a)
print("The datatype of above matrix is",a.dtype)

a1 = np.zeros((2,3))
print(a1)
print(a1.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
The datatype of above matrix is int64
[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [60]:
new = np.array([1+2j,2+3j])   # complex dataype array
print(new.dtype)

complex128


In [61]:
bool1 = np.array([True,False,False,True])              # array with boolean dtype
print(bool1.dtype)

bool


In [62]:
s = np.array(['abc','andy'])
s.dtype

dtype('<U4')

In [64]:
### Character code in numpy arrays

i - signed integer
b - boolean
u - unsigned integer
f - floating point
c - complex floating point
m - timedelta
M - datetime
'S','a' - byte string
U - unicode
'O' - python objects

<class 'numpy.dtype'>


In [65]:
a = np.arange(10)
print(a)
print(a[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [69]:
d = np.diag([1,2,3])
print(d)
print(d[1,2])
print(d[1,1])
print(d[2,2])

d[2,1]=5     # assigning values
print(d)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0
2
3
[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [70]:
## Slicing

a = np.arange(10)
print(a)
a[1:8:2]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7])

In [79]:
a = np.arange(10)
print(a[5:])
a[5:] = 10
print(a)
a[5:]=[1,2,3,4,5]
print(a)
a[5:]= np.random.randn(5)
print(a)
a[5:]= np.random.rand(5)
print(a)

[5 6 7 8 9]
[ 0  1  2  3  4 10 10 10 10 10]
[0 1 2 3 4 1 2 3 4 5]
[0 1 2 3 4 1 0 0 1 0]
[0 1 2 3 4 0 0 0 0 0]


In [81]:
b = np.arange(5)
a[5:]=b[::-1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [ ]:
Copies and Views

In [82]:
a2 = np.arange(10)
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [84]:
b1 = a2[::2]
print(b1)

[0 2 4 6 8]


In [88]:
print(np.shares_memory(a,b))
print(np.shares_memory(a2,b1))

False
True


In [91]:
b1[0]=10
print(b1)
print(a2)               # a2 also changes because b1,a2 shares same memory location

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [92]:
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [94]:
c[0] = 1
print(a)           # because .copy() creates new memory location
np.shares_memory(a,c)

[0 1 2 3 4 5 6 7 8 9]


False

In [102]:
## Fancy indexing

a1 = np.random.randint(1,20,10)
print(a1)
a2 = np.random.randn(1,5)
a2

[ 6  6  6  2 15 15  4 10  6 16]


array([[-1.40271418, -1.57441422,  0.64194265,  1.43870228,  0.85159605]])

In [103]:
a = np.random.randint(1,20,15)
print(a)

[ 7 14  1  4  3  9  4 17  1  3 15 14  9  5  8]


In [111]:
mask = (a%2 == 0)
new = (a%3 == 0)
new1 = (a%2 == 1)

In [112]:
a1 = a[mask]
print(a1)
a3 = a[new1]
print(a3)
a2 = a[new]
a2


[14  4  4 14  8]
[ 7  1  3  9 17  1  3 15  9  5]


array([ 3,  9,  3, 15,  9])

In [113]:
a[mask] = -1
a

array([ 7, -1,  1, -1,  3,  9, -1, 17,  1,  3, 15, -1,  9,  5, -1])

In [ ]:
### assigning values to sub array

In [114]:
## indexing with an array of integers

In [115]:
arr = np.arange(0,100,10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [116]:
arr[[2,3,2,4,5,6]]

array([20, 30, 20, 40, 50, 60])

In [117]:
arr[[3,5,7]] = 200
arr

array([  0,  10,  20, 200,  40, 200,  60, 200,  80,  90])

In [2]:
                              ## Element wise operations
import numpy as np    
    
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
performing opertions with all arthematic on arrays

In [4]:
b = np.ones(4)+1
a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a + b

array([3., 4., 5., 6.])

In [6]:
a/b

array([0.5, 1. , 1.5, 2. ])

In [10]:
(a * b)

array([2., 4., 6., 8.])

In [12]:
## Matrix multiplications

c = np.diag([1,2,3,4])
print(c * c)
print("---------------")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
---------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [13]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a == b

array([False, False, False, False])

In [14]:
a>b

array([False, False, False, False])

In [16]:
## array wise comparisions

np.array_equal(a,b)

False

In [ ]:
                                  ## Logical Operations

In [5]:
import numpy as np
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)
print(np.logical_or(a,b))
print(np.logical_and(a,b))
np.logical_xor(a,b)

[ True  True  True False]
[ True False False False]


array([False,  True,  True, False])

In [7]:
                                 ## Transcendental functions
    
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [8]:
a = np.arange(5)
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [9]:
a = np.arange(5)
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [10]:
a = np.arange(5)
np.log(a)

/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [11]:
                                ## Shape Mismatch
a = np.arange(5)
a + np.array([1,2,3])

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [12]:
# Basic Reductions

In [13]:
a = np.array([1,2,3,4])
np.sum(a)

10

In [15]:
a1 = np.array([[1,2],[2,2]])
a1

array([[1, 2],
       [2, 2]])

In [16]:
np.sum(a1,axis=0)

array([3, 4])

In [18]:
np.sum(a1,axis=1)

array([3, 4])

In [19]:
np.sum(a1,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [20]:
x = np.array([1,2,3,4])
np.min(x)

1

In [21]:
np.max(x)

4

In [22]:
np.argmin(x)

0

In [23]:
np.argmax(x)

3

In [24]:
                                    ## Logical Operations
    
np.all([1,1,1])    

True

In [26]:
np.all([1,1,0])

False

In [27]:
np.all([True,True,True])

True

In [28]:
np.all([True,False,True])

False

In [29]:
np.any([1,0,0])

True

In [30]:
np.any([0,0,0])

False

In [35]:
a = np.zeros([50,50])
print(np.any(a))
print(np.all(a))
print(np.any(a != 0))

False
False
False


In [36]:
np.all(a == a)

True

In [39]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
c = np.array([2,3,4,5])
print(((a<=b)&(b<=c)).all())
((b<=a)&(b>=c)).all()

True


False

In [41]:
                                               # Statistics

In [49]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[2,3,4,5]])
print(np.mean(a))
print(np.mean(b))
print(a.mean())
print(b.mean())

2.5
3.0
2.5
3.0


In [51]:
np.median(a)

2.5

In [52]:
np.median(b,axis=-1)

array([2.5, 3.5])

In [53]:
np.std(a)

1.118033988749895

In [54]:
a.std()

1.118033988749895

In [60]:
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [65]:
year,hares,lynxes,carrots = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [67]:
population = data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [68]:
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [70]:
population.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [71]:
np.argmax(population,axis=1)   # which series has highest population over years

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [72]:
                                        # Broadcasting

In [74]:
a = np.tile(np.array([1,2,3,4]),(3,1))
print(a)
print('----------------------')
a = a.T
print(a)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
----------------------
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [78]:
a1 = np.tile(np.arange(0,30,10),(3,1))
print(a1)
print("--------------")
a1=a1.T
a1

[[ 0 10 20]
 [ 0 10 20]
 [ 0 10 20]]
--------------


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20]])

In [80]:
a2 = np.tile(np.arange(0,30,10),(3,2))
print(a2)
print("--------------")
a2=a2.T
a2

[[ 0 10 20  0 10 20]
 [ 0 10 20  0 10 20]
 [ 0 10 20  0 10 20]]
--------------


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20]])

In [81]:
b = np.array([1,2,3])
a1+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [83]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [85]:
a.shape

(4,)

In [88]:
a = a[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [89]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [90]:
                                      ## Array shape manipulation

In [91]:
a = np.array([[1,2,3],[2,3,4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [92]:
np.ravel(a)

array([1, 2, 3, 2, 3, 4])

In [95]:
b=a.T
b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [96]:
np.ravel(b)

array([1, 2, 2, 3, 3, 4])

In [97]:
b.reshape([2,3])

array([[1, 2, 2],
       [3, 3, 4]])

In [98]:
b.reshape([3,2])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [101]:
a1 = np.arange(4*3*2).reshape(4,3,2)
a1.shape

(4, 3, 2)

In [102]:
a1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [104]:
a1[3,1,1]

21

In [105]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [108]:
np.resize(a,[8,])

array([0, 1, 2, 3, 4, 0, 1, 2])

In [112]:
                                      ## Sorting data
b = np.array([[6,3,4],[3,1,8]])
print(b)
print('-----------------------')
print(np.sort(b,axis=1))
print("-----------------------")
np.sort(b,axis=0)

[[6 3 4]
 [3 1 8]]
-----------------------
[[3 4 6]
 [1 3 8]]
-----------------------


array([[3, 1, 4],
       [6, 3, 8]])

In [113]:
a = np.array([8,4,6,2])
print(a)                   #([8,4,6,2])
                           #([0,1,2,3]) -----> after sorted ([2,4,6,8])
b = np.argsort(a)                                           ([3,1,2,0])
print(b)                    

[8 4 6 2]
[3 1 2 0]
